 # **ALJABAR MATRIKS**

# *Apa itu Matriks ?*

Saat kita bekerja dengan matriks dalam pemrograman, penting untuk memahami dimensi atau ukurannya. Cara kita menyatakan ukuran matriks, dengan menyebutkan jumlah baris terlebih dahulu dan kemudian diikuti oleh jumlah kolom, membantu kita memahami bagaimana matriks tersebut terorganisir. Misalnya, jika kita menyebutkan bahwa matriks A memiliki ukuran 2x2, itu artinya matriks tersebut memiliki 2 baris dan 2 kolom. Demikian juga, jika kita memiliki matriks B yang berukuran 2x3, maka matriks tersebut memiliki 2 baris dan 3 kolom. Dengan pemahaman tentang dimensi matriks ini, kita dapat dengan mudah mengelola dan memanipulasi data matriks dalam konteks pemrograman.

A= $\begin{bmatrix}1 & 2 \\3 & 4\end{bmatrix}$ B= $\begin{bmatrix}1 & 2 & 6 \\3 & 4 & 5\end{bmatrix}$




Umumnya, kita menggunakan variabel dalam subskrip untuk menunjukkan elemen-elemen matriks. Sebagai contoh, $a_{ij}$ menunjukkan elemen di baris ke-$i$ dan kolom ke-$j$ dari matriks A. Dengan notasi ini, kita bisa merujuk dengan mudah ke elemen-elemen tertentu dalam matriks dan melakukan berbagai operasi matematika atau analisis data. Sebuah matriks dengan hanya satu kolom disebut vektor, Tiap elemen dalam vektor diwakili dengan huruf kecil, dengan subskrip yang menunjukkan posisi entri dalam matriks. Sebagai contoh, $B_{12}$ merujuk pada elemen di baris pertama dan kolom kedua dari matriks $B$.

$B_{12}$= $\begin{bmatrix} 2 \end{bmatrix}$



# *Implementasi Matriks menggunakan Numpy*

Implementasi matriks menggunakan NumPy adalah salah satu teknik yang sangat berguna dalam pemrograman Python. NumPy adalah pustaka yang kuat untuk komputasi numerik, dan menyediakan alat yang sangat baik untuk bekerja dengan matriks dan vektor.

Dengan menggunakan NumPy, kita dapat dengan mudah membuat, memanipulasi, dan menghitung matriks dan vektor dalam Python. Misalnya, kita dapat membuat matriks dengan memanggil fungsi seperti `numpy.array()`, dan kemudian mengakses properti `.shape` untuk mengetahui jumlah baris dan kolom dalam matriks tersebut. Misalnya, jika kita memiliki matriks M, kita dapat mengetahui dimensinya dengan menggunakan `M.shape`.Selain itu kita juga dapat melakukan berbagai operasi matematika, seperti penjumlahan, pengurangan, perkalian, dan pembagian matriks.

In [3]:
#Membuat matriks dengan numpy
import numpy as np

A = np.array([[1, 3], [2, 1]])
B = np.array([[3, 0, 4], [-1, -2, 1]])

print('Matriks A:')
print(A)

print('Matriks B:')
print(B)

print(f'Dimensi matriks A: {A.shape}')
print(f'Dimensi matriks B: {B.shape}')


Matriks A:
[[1 3]
 [2 1]]
Matriks B:
[[ 3  0  4]
 [-1 -2  1]]
Dimensi matriks A: (2, 2)
Dimensi matriks B: (2, 3)


Dalam penggunaan pustaka NumPy pada bahasa pemrograman Python, kita mampu membuat matriks acak dengan mudah, sesuai dengan ukuran yang diinginkan. Fungsi `np.random.randint()` biasanya digunakan dalam proses menghasilkan matriks yang terdiri dari bilangan bulat acak dalam rentang 0 hingga 9. Dengan menentukan ukuran matriks melalui parameter `size=(baris, kolom)`, kita dapat membuat matriks dengan dimensi yang spesifik. Setelahnya, dengan menggunakan fungsi `print()`, nilai-nilai dari matriks yang telah dibuat ditampilkan.

In [4]:
#Membuat matriks random menggunakan numpy
import numpy as np

A = np.random.randint(10, size=(3, 3))
B = np.random.randint(10, size=(3, 3))
C = np.random.randint(10, size=(3, 2))
D = np.random.randint(10, size=(3, 3))

print("Matriks A:")
print(A)
print()

print("Matriks B:")
print(B)
print()

print("Matriks C:")
print(C)
print()

print("Matriks D:")
print(D)


Matriks A:
[[3 7 5]
 [7 6 0]
 [8 6 7]]

Matriks B:
[[7 4 9]
 [1 1 1]
 [1 7 3]]

Matriks C:
[[9 6]
 [1 2]
 [2 1]]

Matriks D:
[[5 7 1]
 [5 9 7]
 [0 8 4]]


# *Operasi - Operasi Matriks*

**1. Perkalian Matriks dengan skalar**

Dalam matematika, matriks dapat dikalikan dengan sebuah skalar, yang merupakan bilangan tunggal, baik itu bilangan bulat, pecahan, atau bilangan riil. Proses perkalian ini dilakukan dengan mengalikan setiap elemen dari matriks dengan skalar tersebut. Misalnya, jika kita memiliki matriks A dan kita ingin mengalikannya dengan skalar λ, maka setiap elemen $a_{ij}$ dari matriks A akan dikalikan dengan skalar λ. Hasilnya adalah matriks baru yang memiliki ukuran yang sama dengan matriks awal, tetapi setiap elemennya telah dikalikan dengan skalar tersebut.

$λ.A:=(λ.a_{ij})_{i=1,...,m;j=1,...,n}$

Contoh perhitungan:

$5.\begin{pmatrix}
1 & -3 & 2\\
1 & 2 & 7
\end{pmatrix} = \begin{pmatrix}
5.1 & 5.(-3) & 5.2\\
5.1 & 5.2 & 5.7
\end{pmatrix} = \begin{pmatrix}
5 & -15 & 10\\
5 & 10 & 35
\end{pmatrix}$

In [5]:
#contoh perkalian matriks dengan skalar
import numpy as np

c = 5
AA = c * A 
BB = c * B 
CC = c * C 
DD = c * D 

print("Hasil perkalian skalar c dengan matriks A:")
print(AA)
print()

print("Hasil perkalian skalar c dengan matriks B:")
print(BB)
print()

print("Hasil perkalian skalar c dengan matriks C:")
print(CC)
print()

print("Hasil perkalian skalar c dengan matriks D:")
print(DD)


Hasil perkalian skalar c dengan matriks A:
[[15 35 25]
 [35 30  0]
 [40 30 35]]

Hasil perkalian skalar c dengan matriks B:
[[35 20 45]
 [ 5  5  5]
 [ 5 35 15]]

Hasil perkalian skalar c dengan matriks C:
[[45 30]
 [ 5 10]
 [10  5]]

Hasil perkalian skalar c dengan matriks D:
[[25 35  5]
 [25 45 35]
 [ 0 40 20]]


**2. Penjumlahan 2 buah matriks dengan dimensi yang sama**

Penjumlahan dan pengurangan matriks hanya dapat dilakukan ketika kedua matriks memiliki ukuran yang sama atau setara, yang berarti jumlah baris dan jumlah kolomnya harus identik. Proses penjumlahan atau pengurangan dilakukan dengan cara menambahkan atau mengurangkan elemen-elemen matriks yang memiliki posisi yang sama. Misalnya, elemen pada baris ke-i dan kolom ke-j dari matriks pertama akan dijumlahkan atau dikurangkan dengan elemen pada posisi yang sama dari matriks kedua. Hasil dari operasi ini akan menghasilkan matriks baru yang juga memiliki ukuran yang sama seperti matriks asal, dengan setiap elemen pada posisi yang sesuai berisi hasil penjumlahan atau pengurangan dari elemen-elemen yang bersesuaian dalam matriks-matriks tersebut.

$a_{ij}\pm b_{ij}=c_{ij}$

atau 

$\begin{bmatrix}
a_{11}\pm b_{11} & a_{12}\pm b_{12} & a_{13}\pm b_{13} \\
a_{21}\pm b_{21} & a_{22}\pm b_{22} & a_{23}\pm b_{23}
\end{bmatrix}$ = $\begin{bmatrix}
c_{11} & c_{12} & c_{13}\\
c_{21} & c_{22} & c_{23}
\end{bmatrix}$



In [8]:
#contoh penjumlahan 2 buah matriks yang sama.
import numpy as np

k = AA + BB

print(f"A:\n{AA}")
print(f"B:\n{BB}")
print(f"k = A + B:\n{k}")


A:
[[15 35 25]
 [35 30  0]
 [40 30 35]]
B:
[[35 20 45]
 [ 5  5  5]
 [ 5 35 15]]
k = A + B:
[[50 55 70]
 [40 35  5]
 [45 65 50]]


**3. Perkalian matriks**

Dalam matematika, terdapat metode perkalian matriks yang disebut perkalian titik (atau perkalian matriks standar), di mana setiap elemen baris dari matriks pertama dikalikan dengan setiap elemen kolom dari matriks kedua, dan hasilnya dijumlahkan untuk mendapatkan elemen baru pada matriks hasil. Dengan cara ini, kita dapat menggabungkan informasi dari setiap baris matriks pertama dengan setiap kolom matriks kedua untuk mendapatkan matriks baru yang mewakili hubungan yang kompleks antara keduanya. Proses ini dapat diulangi untuk setiap baris matriks pertama dan setiap kolom matriks kedua hingga semua elemen matriks hasil terisi.

$c_{ij}=\sum_{k=1}^m a_{ik}.b_{kj}$

Contoh perhitungan:

$\begin{pmatrix}
1 & 2 & 3\\
4 & 5 & 6
\end{pmatrix}.\begin{pmatrix}
6 & -1 \\
3 & 2 \\
0 & -3
\end{pmatrix} = \begin{pmatrix}
1.6+2.3+3.0 & 1.(-1)+2.2+3.(-3)\\
4.6+5.3+6.0 & 4.(-1)+5.2+6.(-3) 
\end{pmatrix} = \begin{pmatrix}
12 & -6 \\
39 & -12 
\end{pmatrix}$

**- Sifat-Sifat Matriks** 

Sifat-sifat matriks sebagai berikut :

$1. A+B=B+A$

$2. (A+B)+C=A+(B+C)$

$3. k(AB)=(kA)B$

$4. (AB)C=(BC)$

$5. A(B+C)=AB+AC$

$6. (A+B)C=AC+BC$

$7. AB≠BA$



In [10]:
#cara 1 menggunakan numpy
import numpy as np

# Matriks A
print(f'A:\n{A}\ndimensi: {A.shape}\n')

# Matriks B
print(f'B:\n{B}\ndimensi: {B.shape}\n')

# Perkalian matriks A dan B
AB = np.dot(A, B)
print('Matriks AB:')
print(AB)


A:
[[3 7 5]
 [7 6 0]
 [8 6 7]]
dimensi: (3, 3)

B:
[[7 4 9]
 [1 1 1]
 [1 7 3]]
dimensi: (3, 3)

Matriks AB:
[[33 54 49]
 [55 34 69]
 [69 87 99]]


In [11]:
#cara 2 menggunakan @
import numpy as np

# Matriks A
print(f'Matriks A:\n{A}\nDimensi: {A.shape}\n')

# Matriks B
print(f'Matriks B:\n{B}\nDimensi: {B.shape}\n')

# Perkalian matriks A dan B
AB = A @ B
print('Hasil perkalian matriks A dan B:')
print(AB)


Matriks A:
[[3 7 5]
 [7 6 0]
 [8 6 7]]
Dimensi: (3, 3)

Matriks B:
[[7 4 9]
 [1 1 1]
 [1 7 3]]
Dimensi: (3, 3)

Hasil perkalian matriks A dan B:
[[33 54 49]
 [55 34 69]
 [69 87 99]]


In [12]:
# Menggunakan iterasi
A = [[1, 3],
     [2, 1]]
B = [[3, 0, 4],
     [-1, -2, 1]]
C = [[0, 0, 0],
     [0, 0, 0]]
for i in range(2):
    for j in range(3):
        for k in range(2):
            C[i][j] += A[i][k] * B[k][j]
print("Hasil perkalian matriks:")
for row in C:
    print(row)

Hasil perkalian matriks:
[0, -6, 7]
[5, -2, 9]


# *Matriks Transpose*

Transpose matriks adalah operasi yang menghasilkan matriks baru dengan menukar posisi baris dan kolom dari matriks asalnya. Dengan kata lain, setiap elemen yang berada di baris i dan kolom j pada matriks asal akan menjadi elemen yang berada di baris j dan kolom i pada matriks transposenya

Contoh : 

$B= \begin{bmatrix}1 & 2 & 6 \\3 & 4 & 5\end{bmatrix}$

$B^T= \begin{bmatrix}1 & 3\\2 & 4\\6 & 5 \end{bmatrix}$

In [14]:
#contoh matriks transpose
import numpy as np

# Matriks A
print(f'Matriks A:\n{AA}\n')

# Matriks B
print(f'Matriks B:\n{BB}\n')

# Transpose matriks A dan B
A_T = AA.transpose()
B_T = BB.transpose()

# Matriks transpose A dan B
print(f'Transpose dari matriks A:\n{A_T}\n')
print(f'Transpose dari matriks B:\n{B_T}\n')


Matriks A:
[[15 35 25]
 [35 30  0]
 [40 30 35]]

Matriks B:
[[35 20 45]
 [ 5  5  5]
 [ 5 35 15]]

Transpose dari matriks A:
[[15 35 40]
 [35 30 30]
 [25  0 35]]

Transpose dari matriks B:
[[35  5  5]
 [20  5 35]
 [45  5 15]]



# *Matriks Elementer*
Matriks elementer adalah matriks yang diperoleh dari matriks identitas melalui satu atau lebih operasi baris elementer. Matriks identitas adalah matriks persegi yang memiliki nilai 1 di sepanjang diagonal utamanya dan nilai 0 di tempat lainnya. Operasi baris elementer adalah operasi dasar yang dapat dilakukan pada baris-baris matriks, seperti menukar dua baris, mengalikan baris dengan skalar non-nol, atau menambahkan satu baris dengan baris lainnya yang telah dikalikan dengan skalar tertentu.
Tentu, berikut adalah contoh matriks elementer yang diperoleh dari matriks identitas 2x2 dengan menerapkan beberapa operasi baris elementer:

1. Mulai dengan matriks identitas 2x2:
$ I = \begin{bmatrix} 
1 & 0 \\
0 & 1 \\
\end{bmatrix} $

2. Misalkan kita ingin menukar baris pertama dengan baris kedua. Kita dapat melakukan operasi baris elementer untuk mencapai ini:
$ \begin{bmatrix} 
0 & 1 \\
1 & 0 \\
\end{bmatrix} $

3. Kemudian, kita mungkin ingin mengalikan baris kedua dengan 3:
$ \begin{bmatrix} 
0 & 1 \\
3 & 0 \\
\end{bmatrix} $

4. Selanjutnya, kita bisa menambahkan baris kedua dengan baris pertama:
$ \begin{bmatrix} 
3 & 1 \\
3 & 0 \\
\end{bmatrix} $

Matriks di atas adalah contoh dari matriks elementer yang diperoleh dari matriks identitas dengan menerapkan beberapa operasi baris elementer. Dengan cara ini, kita dapat membentuk berbagai matriks elementer yang berbeda dengan menerapkan operasi baris elementer pada matriks identitas asli.

In [2]:
import sympy as sy

# Matriks acak A
A = sy.randMatrix(3)
print("Matriks A:")
print(A)

# Matriks baris elementer E
E = sy.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
print("Matriks E:")
print(E)

# Operasi baris elementer E pada matriks A
result = E * A
print("Hasil operasi baris elementer E pada matriks A:")
print(result)


Matriks A:
Matrix([[37, 65, 19], [96, 99, 30], [35, 69, 4]])
Matriks E:
Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
Hasil operasi baris elementer E pada matriks A:
Matrix([[96, 99, 30], [37, 65, 19], [35, 69, 4]])


# *referensi*  
1). [(https://id.wikipedia.org/wiki/Matriks_(matematika))](https://id.wikipedia.org/wiki/Matriks_(matematika))

2). [https://www.youtube.com/watch?v=z6xfiHUuWWQ&list=PLZS-MHyEIRo6V6C2PHEx2Lt0hWIB_cL58&index=5](https://www.youtube.com/watch?v=z6xfiHUuWWQ&list=PLZS-MHyEIRo6V6C2PHEx2Lt0hWIB_cL58&index=5)

3). [https://numpy.org/doc/stable/reference/generated/numpy.matrix.html](https://numpy.org/doc/stable/reference/generated/numpy.matrix.html)