 # **DETERMINAN MATRIKS**

# 1. Determinan dari matriks identitas adalah 1 
Ini adalah sifat yang mendasar. Matriks identitas adalah matriks persegi di mana semua elemen diagonalnya adalah 1 dan elemen lainnya adalah 0. Karena transformasi identitas tidak mengubah volume, determinannya adalah 1.

In [3]:
# Kita buat matriks terlebih dahulu dengan numpy
import numpy as np

A=np.array([[1,2],[2,3]])
C=np.array([[1,0],[0,1]])

print('Matriks A 2x2 :')
print(A)
print('Matriks Identitas A :')
print(C)
print()

Matriks A 2x2 :
[[1 2]
 [2 3]]
Matriks Identitas A :
[[1 0]
 [0 1]]



In [4]:
#Pembuktian untuk Determinan dari Matriks Identitas adalah 1
import numpy as np
from numpy import linalg as LA

print('Determinan dari Matriks Identitas adalah 1 :')
print(np.linalg.det(C))

Determinan dari Matriks Identitas adalah 1 :
1.0


# 2. Determinan Matriks Invers

Ketika kita mengalikan determinan suatu matriks dengan determinan inversnya, kita mendapatkan hasil yang selalu sama, yaitu 1. Ini merupakan sifat yang penting dari invers matriks dan determinan.

In [5]:
# Pembuktian bahwa determinan matriks dikalikan determinan matriks inversnya akan menghasilkan nilai determinan yaitu 1

import numpy as np

A_invers=np.linalg.inv(A)
print('invers A :')
print(A_invers)

hasil=np.linalg.det(A) * np.linalg.det(A_invers)

print('determinan : ')
print(round(hasil))


invers A :
[[-3.  2.]
 [ 2. -1.]]
determinan : 
1


# 3. Determinan dari hasil perkalian matriks
Jika hasil perkalian dua matriks adalah matriks persegi, maka determinan dari hasil perkalian tersebut sama dengan perkalian determinan masing-masing matriks. 

In [6]:
import numpy as np

E=np.array([[3,5,1],[2,6,2],[1,3,1]])
F=np.array([[1,1,2],[1,1,3],[2,1,2]])
print('Matriks E = ')
print(E)
print('Matriks F = ')
print(F)
print()
G= E@F
detG=np.linalg.det(G)
print('Matriks G = Matriks E x Matriks F')
print(G)
print()
print('Determinan Matriks G')
print(detG)

detEF=np.linalg.det(E)*np.linalg.det(F)
print('Determinan Matriks EF')
print(detEF)

Matriks E = 
[[3 5 1]
 [2 6 2]
 [1 3 1]]
Matriks F = 
[[1 1 2]
 [1 1 3]
 [2 1 2]]

Matriks G = Matriks E x Matriks F
[[10  9 23]
 [12 10 26]
 [ 6  5 13]]

Determinan Matriks G
0.0
Determinan Matriks EF
0.0


# 4.  Efek pertukaran baris
Ketika baris-baris matriks ditukar, determinannya akan berubah tanda. Misalnya, jika dua baris ditukar, determinannya akan menjadi negatif dari nilai sebelumnya. 



In [7]:
#Pembuktian apabila matriks a diubah posisi baris atau kolom nya akan merubah tandanya
import numpy as np

a=np.array([[1,4,2],[1,1,1],[3,2,1]])
a1=np.array([[1,1,1],[1,4,2],[3,2,1]])
a2=np.array([[4,1,2],[1,1,1],[2,3,1]])
a3=np.array([[1,2,4],[1,1,1],[3,1,2]])

det_a=np.linalg.det(a)
det_a1=np.linalg.det(a1)
det_a2=np.linalg.det(a2)
det_a3=np.linalg.det(a3)
print(round(det_a))
print(round(det_a1))
print(round(det_a2))
print(round(det_a3))

5
-5
-5
-5


In [8]:
#Pembuktian jika baris dari matriks merupakan kelipatan dari baris atau kolom yang lain maka akan menghasilkan 0
import numpy as np

aa=np.array([[1,4,2],[2,8,4],[3,2,1]])
bb=np.array([[1,4,2],[2,8,3],[1,4,1]])

det_aa=np.linalg.det(aa)
det_bb=np.linalg.det(bb)
print(aa)
print(det_aa)
print()
print(bb)
print(det_bb)


[[1 4 2]
 [2 8 4]
 [3 2 1]]
0.0

[[1 4 2]
 [2 8 3]
 [1 4 1]]
0.0


# 4. Pengaruh skalar pada determinan: 
Jika matriks dikalikan dengan skalar 
𝑘
k, determinan dari matriks tersebut akan menjadi 
𝑘
k kali determinan aslinya. 

In [20]:
import numpy as np

a=np.array([[1,4,2],[1,1,1],[3,2,1]])
print('Matriks Awal : ')
print('determinannya :')
print(np.linalg.det(a))
k = 2
temp = k*a[0]
print(temp) 
print()
A=np.array([[2,8,4],[1,1,1],[3,2,1]])
print('mengalikan matriks baris 1 dengan skalar : ')
print(A)
print('determinannya :')
det_A=np.linalg.det(A)
print(det_A)

Matriks Awal : 
determinannya :
5.000000000000001
[2 8 4]

mengalikan matriks baris 1 dengan skalar : 
[[2 8 4]
 [1 1 1]
 [3 2 1]]
determinannya :
10.000000000000002


# 5. Determinan matriks segitiga
Determinan dari matriks segitiga (baik segitiga atas maupun bawah) dapat dihitung dengan mengalikan setiap elemen pada diagonal utamanya. Ini disebabkan karena matriks segitiga hanya memiliki elemen di sepanjang diagonal utama, dan elemen lainnya nol. Maka, determinan dihitung hanya dari elemen-elemen diagonal ini.

In [25]:
import numpy as np

x=np.array([[1,5,6],[0,3,4],[0,0,4]])

print('Matriks X :')
print(x)
print('determinannya :')
temp=np.linalg.det(x)
print(temp)

Matriks X :
[[1 5 6]
 [0 3 4]
 [0 0 4]]
determinannya :
12.0


# Mencari determinan matriks 4x4 menggunakan ekspansi kofaktor

1. Buat matriks 4 x 4 terlebih dahulu

$ A= \begin{bmatrix} &1 & 2 & 1 & 2 \\ & 0 & 2 & 3 & 0 \\ &3 & 1 & 0 & 1 \\ &2 & 3 & 1 & 0 \end{bmatrix} $

2. Mencari determinan matriks dari salah satu baris matriks A.

disini semisal saya menggunakan baris 2.

$A_{21}c_{21}+A_{22}c_{22}+A_{23}c_{23}+A_{24}c_{24}$

3. Cari terlebih dahulu kofaktor nya
$c_{21}=(-1)^{2+1}det(M_{21})$

$c_{22}=(-1)^{2+2}det(M_{22})$

$c_{23}=(-1)^{2+3}det(M_{23})$

$c_{24}=(-1)^{2+4}det(M_{24})$

untuk mencari kofaktor kita perlu mencari determinan minornya

- Determinan M21

$M_{21} = \begin{bmatrix} & 2 & 1 & 2 \\ & 1 & 0 & 1 \\ &3 & 1 & 0 \end{bmatrix}$

Menggunakan  baris ke 2:

$c_{21}=(-1)^{2+1}.(-2)=(-1).(-2)=2$

$c_{22}=(-1)^{2+2}.(-6)=1.(-6)=-6$

$c_{23}=(-1)^{2+3}.(-1)=(-1).(-1)=1$

$M_{21}=a_{21}c_{21}+a_{22}c_{22}+a_{23}c_{23}$

$M_{21}=1.2+0.-6+1.1$

$M_{21}=3$

- Determinan M22

$M_{22} = \begin{bmatrix} & 1 & 1 & 2 \\ & 3 & 0 & 1 \\ &2 & 1 & 0 \end{bmatrix}$

Menggunakan  baris ke 2:

$c_{21}=(-1)^{2+1}.(-2)=(-1).(-2)=2$

$c_{22}=(-1)^{2+2}.(-4)=1.(-4)=-4$

$c_{23}=(-1)^{2+3}.(-1)=(-1).(-1)=1$

$M_{22}=a_{21}c_{21}+a_{22}c_{22}+a_{23}c_{23}$

$M_{22}=3.2+0.-4+1.1$

$M_{22}=7$

- Determinan M23

$M_{23} = \begin{bmatrix} & 1 & 2 & 2 \\ & 3 & 1 & 1 \\ &2 & 3 & 0 \end{bmatrix}$

Menggunakan  baris ke 2:

$c_{21}=(-1)^{2+1}.(-6)=(-1).(-6)=6$

$c_{22}=(-1)^{2+2}.(-4)=1.(-4)=-4$

$c_{23}=(-1)^{2+3}.(-1)=(-1).(-1)=1$

$M_{23}=a_{21}c_{21}+a_{22}c_{22}+a_{23}c_{23}$

$M_{23}=3.6+1.-4+1.1$

$M_{23}=15$

- Determinan M24

$M_{24} = \begin{bmatrix} & 1 & 2 & 1 \\ & 3 & 1 & 0 \\ &2 & 3 & 1 \end{bmatrix}$

Menggunakan  baris ke 2:

$c_{21}=(-1)^{2+1}.(-1)=(-1).(-1)=1$

$c_{22}=(-1)^{2+2}.(-1)=1.(-1)=-1$

$c_{23}=(-1)^{2+3}.(-1)=(-1).(-1)=1$

$M_{24}=a_{21}c_{21}+a_{22}c_{22}+a_{23}c_{23}$

$M_{24}=3.1+1.-1+0.1$

$M_{24}=2$

Subtitusikan nilai nilai determinan dari matriks minor ke setiap persamaan kofaktor=

$c_{21}=(-1)^{2+1}det(M_{21})=-1.3 = -3$

$c_{22}=(-1)^{2+2}det(M_{22})=1.7 = 7$

$c_{23}=(-1)^{2+3}det(M_{23})=-1.15 = -15$

$c_{24}=(-1)^{2+4}det(M_{24})=1.2 = 2$

setelah kita mengetahui masing masing nilai kofaktor pada elemen baris ke 2 matriks A.

$det(A) =a_{21}c_{21}+a_{22}c_{22}+a_{23}c_{23}+a_{24}c_{24}$

$det(A) =0.-3 + 2.7 + 3.-15 + 0.2$

$det(A) =-31$

Jadi determinan Matriks A adalah -31


In [28]:
#Pembuktian Perhitungan manual tadi

y=np.array([[1,2,1,2],[0,2,3,0],[3,1,0,1],[2,3,1,0]])

det=np.linalg.det(y)
print(y)
print(det)

[[1 2 1 2]
 [0 2 3 0]
 [3 1 0 1]
 [2 3 1 0]]
-31.0
