# **EIGEN VALUE DAN EIGEN VECTOR**

# *Konsep Eigen Value dan Eigen Vector*

Dalam aljabar linear, vektor eigen adalah vektor yang arahannya tetap sama ketika dikalikan dengan matriks, hanya panjangnya yang berubah. Perubahan panjang ini disebut nilai eigen, yang dilambangkan dengan $\lambda$. Jika matriks $A$ dikalikan dengan vektor eigen $v$, hasilnya adalah $A$ $\cdot$ $v$ = $\lambda$ $\cdot$ $v$. Ruang eigen adalah kumpulan semua vektor yang tetap berada dalam ruang tersebut ketika dikalikan dengan matriks, termasuk vektor nol dan vektor-vektor eigen yang terkait dengan nilai eigen tertentu. Vektor dan nilai eigen sangat berguna dalam berbagai aplikasi, seperti analisis data dan pemrosesan sinyal, karena membantu memahami transformasi pada ruang multidimensi.

# *Mencari nilai Eigen Value dan Eigen Vector*

# Matriks 2x2

Misalkan ada matriks $A$ berikut:

$A$ = $\begin{bmatrix} 2 & 1 \\ 1 & 2 \end{bmatrix}$

Vektor-vektor eigen $v$ dari matriks ini adalah vektor-vektor yang arahannya tetap sama setelah dikalikan dengan matriks, hanya panjangnya yang berubah. Nilai eigen $\lambda$ adalah faktor perubahan panjang tersebut. Untuk mencari nilai eigen, kita menghitung determinan matriks $A$ - $\lambda$ $I$ dan menyamakannya dengan nol. Hasilnya adalah polinomial karakteristik:

$A$ - $\lambda$ $I$ = $\begin{vmatrix} 2 - \lambda & 1 \\ 1 & 2 - \lambda \end{vmatrix}$ = ($\lambda$ - 3)($\lambda$ - 1).


Akar-akarnya adalah $\lambda$ = 1 dan $\lambda$ = 3, yang merupakan nilai-nilai eigen dari $A$.

Untuk $\lambda$ = 1, substitusi ke dalam $A - I$ menghasilkan:

$(A - I)v$ = $\begin{bmatrix} 1 & 1 \\ 1 & 1 \end{bmatrix} \begin{bmatrix} v_1 \\ v_2 \end{bmatrix}$ = $\begin{bmatrix} 0 \\ 0 \end{bmatrix}$

yang berarti $v_1 = -v_2$. Salah satu vektor eigennya adalah:

$v_{\lambda=1} = \begin{bmatrix} 1 \\ -1 \end{bmatrix}.$

Untuk $\lambda$ = 3, substitusi ke dalam $A - 3I$ menghasilkan:

$(A - 3I)v$ = $\begin{bmatrix} -1 & 1 \\ 1 & -1 \end{bmatrix}$ $\begin{bmatrix} v_1 \\ v_2 \end{bmatrix}$ = $\begin{bmatrix} 0 \\ 0 \end{bmatrix}$

yang berarti $v_1 = v_2$. Salah satu vektor eigennya adalah:

$v_{\lambda=3}$ = $\begin{bmatrix} 1 \\ 1 \end{bmatrix}.$

Jadi, vektor  $\begin{bmatrix} 1 \\ -1 \end{bmatrix}$ adalah vektor eigen yang berhubungan dengan nilai eigen $\lambda = 1$, dan vektor $ \begin{bmatrix} 1 \\ 1 \end{bmatrix} $ adalah vektor eigen yang berhubungan dengan nilai eigen $\lambda = 3$.

In [3]:
#Pembuktian Menggunakan Numpy
import numpy as np
from numpy.linalg import eig

# Definisikan matriks A
A = np.array([[2,1], [1, 2],])

# Hitung eigenvalues dan eigenvectors
eigenvalues, eigenvectors = eig(A)

# Bulatkan hasilnya
rounded_eigenvalues = np.round(eigenvalues)
rounded_eigenvectors = np.round(eigenvectors)

# Cetak hasilnya
print("Eigenvalues:")
print(rounded_eigenvalues)
print("\nEigenvectors:")
print(rounded_eigenvectors)


Eigenvalues:
[3. 1.]

Eigenvectors:
[[ 1. -1.]
 [ 1.  1.]]


# Matriks 3x3

matriks $\mathbf{A}$ = $\begin{bmatrix} 4 & 1 & 1 \\ 1 & 4 & 1 \\ 1 & 1 & 4 \end{bmatrix}$.

*Langkah 1: Mencari Eigen Value*

Eigen value $\lambda$ adalah nilai-nilai yang memenuhi persamaan berikut:
$\text{det}\mathbf{A} - \lambda \mathbf{I}$ = 0
di mana \(\mathbf{I}\) adalah matriks identitas.

1.1. Buat matriks $\mathbf{A} - \lambda \mathbf{I}$:

$\mathbf{A} - \lambda \mathbf{I}$ = $\begin{bmatrix} 4 - \lambda & 1 & 1 \\ 1 & 4 - \lambda & 1 \\ 1 & 1 & 4 - \lambda \end{bmatrix}$

1.2. Hitung determinan dari matriks tersebut dan buat persamaan karakteristik:

$\text{det}(\mathbf{A} - \lambda \mathbf{I}) = \begin{vmatrix} 4 - \lambda & 1 & 1 \\ 1 & 4 - \lambda & 1 \\ 1 & 1 & 4 - \lambda \end{vmatrix}$

Untuk matriks 3x3, determinan dapat dihitung dengan ekspansi kofaktor:

= $(4-\lambda)\begin{vmatrix} 4-\lambda & 1 \\ 1 & 4-\lambda \end{vmatrix}$ - $1\begin{vmatrix} 1 & 1 \\ 1 & 4-\lambda \end{vmatrix}$ + $1\begin{vmatrix} 1 & 4-\lambda \\ 1 & 1 \end{vmatrix}$

Hitung determinan 2x2 di dalamnya:

$\begin{vmatrix} 4-\lambda & 1 \\ 1 & 4-\lambda \end{vmatrix}$ = $(4-\lambda)(4-\lambda) - 1 \cdot 1$ = $(4-\lambda)^2 - 1$

$\begin{vmatrix} 1 & 1 \\ 1 & 4-\lambda \end{vmatrix}$ = $1 \cdot (4-\lambda) - 1 \cdot 1$ = $4 - \lambda - 1$ = $3 - \lambda$

$\begin{vmatrix} 1 & 4-\lambda \\ 1 & 1 \end{vmatrix}$ = $1 \cdot 1 - (4-\lambda) \cdot 1$ = $1 - (4-\lambda)$ = $\lambda - 3$

Masukkan kembali ke dalam ekspansi kofaktor:

= $(4-\lambda)((4-\lambda)^2 - 1) - (3 - \lambda) + (\lambda - 3)$

Sederhanakan:

= $(4-\lambda)(\lambda^2 - 8\lambda + 15) - (3 - \lambda) + (\lambda - 3)$

Gabungkan semua suku:

= $-\lambda^3 + 12\lambda^2 - 42\lambda + 54 = 0$

Maka, kita menyelesaikan persamaan kubik $-\lambda^3 + 12\lambda^2 - 42\lambda + 54 = 0$ untuk mendapatkan eigen values. Misalnya, kita temukan $\lambda = 6$, $\lambda = 3$, dan $\lambda = 3$.

*Langkah 2: Mencari Eigen Vector*

Setelah mendapatkan eigen values, kita mencari eigen vector (\(\mathbf{v}\)) dengan menyelesaikan sistem persamaan:

$\mathbf{A} - \lambda \mathbf{I}) \mathbf{v} = 0$

Misal $\lambda = 6$ adalah salah satu eigen value.

2.1. Buat matriks $\mathbf{A} - 6\mathbf{I}$:

$\mathbf{A} - 6\mathbf{I}$ = $\begin{bmatrix} -2 & 1 & 1 \\ 1 & -2 & 1 \\ 1 & 1 & -2 \end{bmatrix}$

2.2. Selesaikan sistem persamaan:

$\begin{bmatrix} -2 & 1 & 1 \\ 1 & -2 & 1 \\ 1 & 1 & -2 \end{bmatrix}$ $\begin{bmatrix} x \\ y \\ z \end{bmatrix}$ = $\begin{bmatrix} 0 \\ 0 \\ 0 \end{bmatrix}$

Dari sini, kita bisa menggunakan eliminasi Gauss atau metode lain untuk menemukan vektor eigen $\mathbf{v}$.

Hasilnya akan memberikan eigen values dan eigen vectors untuk matriks $\mathbf{A}$.

In [4]:
import numpy as np
from numpy.linalg import eig

# Definisikan matriks A
A = np.array([[4, 1, 1], 
              [1, 4, 1], 
              [1, 1, 4]])

# Hitung nilai eigen dan vektor eigen
eigenvalues, eigenvectors = eig(A)

# Bulatkan hasilnya untuk kemudahan interpretasi
rounded_eigenvalues = np.round(eigenvalues)
rounded_eigenvectors = np.round(eigenvectors)

# Cetak hasilnya
print("Eigenvalues:")
print(rounded_eigenvalues)
print("\nEigenvectors:")
print(rounded_eigenvectors)


Eigenvalues:
[6. 3. 3.]

Eigenvectors:
[[-1. -1. -0.]
 [-1.  0. -1.]
 [-1.  0.  1.]]


# *Contoh implementasi Nilai Eigen Value dan Eigen Vector*

In [4]:
import numpy as np

def pcaEVD(X):
    n, p = X.shape
    X_centered = X - X.mean(axis=0)
    C = (X_centered.T @ X_centered) / (n - 1)
    e_vals, e_vecs = np.linalg.eig(C)
    
    idx = e_vals.argsort()[::-1]
    e_vals = e_vals[idx]
    e_vecs = e_vecs[:, idx]
    
    return (X_centered @ e_vecs), e_vals, e_vecs

X = np.array([[3, 2],
              [2, 3]])

components, eigenvalues, eigenvectors = pcaEVD(X)

rounded_components = np.round(components)
rounded_eigenvalues = np.round(eigenvalues)
rounded_eigenvectors = np.round(eigenvectors)

print("Components:\n", rounded_components)
print("Eigenvalues:\n", rounded_eigenvalues)
print("Eigenvectors:\n", rounded_eigenvectors)


Components:
 [[ 1. -0.]
 [-1.  0.]]
Eigenvalues:
 [1. 0.]
Eigenvectors:
 [[ 1.  1.]
 [-1.  1.]]


# *Referensi*

1). [https://id.wikipedia.org/wiki/Nilai_dan_vektor_eigen](https://id.wikipedia.org/wiki/Nilai_dan_vektor_eigen)
