 # **MATRIKS INVERS**

# *Apa itu Matriks Invers?* 

Invers matriks adalah suatu konsep dalam aljabar linear yang mengacu pada kebalikan dari sebuah matriks. Jika kita memiliki sebuah matriks $ A $, inversnya, dilambangkan sebagai $ A^{-1}$, adalah matriks yang ketika dikalikan dengan matriks aslinya, menghasilkan matriks identitas. Dengan kata lain, jika $ A \times A^{-1} = I $, di mana $ I $ adalah matriks identitas, maka $ A^{-1} $ adalah invers dari $ A $.


# *Sifat-sifat Matriks Invers*

Sifat-sifat dari invers matriks:

1. **Hanya untuk Matriks Persegi**: Invers matriks hanya bisa ada untuk matriks yang punya jumlah baris dan kolom sama.
2. **Hanya untuk Matriks Non-singular**: Invers matriks hanya ada jika determinan matriksnya tidak nol. Determinan itu adalah nilai yang dihitung dari unsur-unsur matriks persegi.
3. **Hanya Ada Satu Invers**: Setiap matriks punya satu invers saja. Kalau $ B $ dan $ C $ keduanya invers dari $ A $, berarti $ B $ sama dengan $ C $.
4. **Invers dari Invers adalah Matriks Itu Sendiri**: Kalau $ B $ adalah invers dari $ A $, maka invers dari $ B $ adalah $ A $. Jadi, $ (A^{-1})^{-1} = A $.
5. **Invers dari Hasil Kali Matriks**: Invers dari hasil kali dua matriks adalah hasil kali invers masing-masing matriks dalam urutan terbalik. Misalnya, kalau $ A $ dan $ B $ keduanya tidak nol, maka $ (AB)^{-1} = B^{-1}A^{-1} $.
6. **Invers dari Transpos Matriks**: Invers dari transpos suatu matriks adalah transpos dari inversnya. Transpos itu adalah menukar baris dan kolom. Kalau $ A $ tidak nol, maka $ (A^T)^{-1} = (A^{-1})^T $.

# *Metode Gauss-Jordan untuk Mencari Invers Matriks*

Metode Gauss-Jordan adalah teknik yang digunakan untuk menemukan invers dari sebuah matriks. Ini melibatkan transformasi matriks asli menjadi matriks identitas dengan menggunakan serangkaian operasi baris, dan saat operasi ini diterapkan pada matriks identitas yang terhubung, matriks asli akan berubah menjadi inversnya.

Langkah-langkah umumnya adalah sebagai berikut:

1. **Susun Matriks Gabungan**: Susun matriks gabungan dari matriks yang ingin diinvers ($ A $) dan matriks identitas ($ I $). Matriks identitas ditempatkan di sebelah kanan matriks $ A $.

2. **Gunakan Operasi Baris**: Terapkan operasi baris untuk mengubah matriks gabungan menjadi bentuk echelon atau bentuk tereduksi. Ini melibatkan operasi tambah, kurang, kali, atau bagi baris untuk mencapai 0 di bawah elemen diagonal utama.

3. **Ubah Menjadi Identitas**: Selanjutnya, terapkan operasi baris lanjutan untuk mengubah matriks echelon menjadi bentuk identitas. Ini dilakukan dengan memastikan setiap baris memiliki 1 di posisi diagonal utama, dan semua elemen di atas dan di bawah diagonal utama adalah 0.

4. **Interpretasi Hasil**: Matriks di sebelah kanan matriks gabungan akan menjadi invers dari matriks asli $ A $.

5. **Periksa Hasil**: Pastikan untuk memverifikasi bahwa matriks hasil memenuhi kriteria invers, yaitu ketika dikalikan dengan matriks asli, menghasilkan matriks identitas.

*Contoh :*

Kita akan mencari invers dari matriks:
$ A = \begin{bmatrix} 3 & 1 & 4 \\ 1 & 5 & 9 \\ 2 & 6 & 5 \end{bmatrix} $

1. **Susun Matriks Gabungan**:
   Matriks gabungan dari $ A $ dan matriks identitas ($ I $) adalah:
   $ \begin{bmatrix} 3 & 1 & 4 & | & 1 & 0 & 0 \\ 1 & 5 & 9 & | & 0 & 1 & 0 \\ 2 & 6 & 5 & | & 0 & 0 & 1 \end{bmatrix} $

2. **Gunakan Operasi Baris**:
   - Langkah pertama adalah membuat 0 di bawah elemen pertama di baris pertama. Kita kurangkan baris kedua dengan $ \frac{1}{3} \times $ baris pertama dan kurangkan baris ketiga dengan $ \frac{2}{3} \times $ baris pertama. Ini memberikan kita matriks:
   $ \begin{bmatrix} 3 & 1 & 4 & | & 1 & 0 & 0 \\ 0 & \frac{14}{3} & \frac{29}{3} & | & -\frac{1}{3} & 1 & 0 \\ 0 & \frac{4}{3} & -\frac{3}{3} & | & -\frac{2}{3} & 0 & 1 \end{bmatrix} $
   - Kemudian, untuk membuat 0 di bawah elemen kedua di baris kedua, kita kurangkan baris ketiga dengan $ \frac{4}{14} \times $ baris kedua. Ini memberikan kita:
   $ \begin{bmatrix} 3 & 1 & 4 & | & 1 & 0 & 0 \\ 0 & \frac{14}{3} & \frac{29}{3} & | & -\frac{1}{3} & 1 & 0 \\ 0 & 0 & -\frac{17}{14} & | & -\frac{5}{14} & -\frac{4}{14} & 1 \end{bmatrix} $

3. **Ubah Menjadi Identitas**:
   - Sekarang kita ubah elemen diagonal menjadi 1. Kita bagi baris pertama dengan $ 3 $, baris kedua dengan $ \frac{14}{3} $, dan baris ketiga dengan $ -\frac{17}{14} $. Ini memberikan kita:
   $ \begin{bmatrix} 1 & \frac{1}{3} & \frac{4}{3} & | & \frac{1}{3} & 0 & 0 \\ 0 & 1 & \frac{29}{42} & | & -\frac{1}{14} & \frac{3}{14} & 0 \\ 0 & 0 & 1 & | & \frac{5}{17} & \frac{4}{17} & -\frac{14}{17} \end{bmatrix} $

4. **Operasi Baris Lanjutan**:
   - Kita lanjutkan dengan mengubah elemen di atas diagonal menjadi 0. Kita kurangkan baris pertama dengan $ \frac{1}{3} \times $ baris kedua dan kurangkan baris kedua dengan $ \frac{29}{42} \times $ baris ketiga. Ini memberikan kita:
   $ \begin{bmatrix} 1 & 0 & 0 & | & \frac{1}{2} & -\frac{1}{6} & 0 \\ 0 & 1 & 0 & | & \frac{1}{2} & \frac{1}{6} & -\frac{14}{3} \\ 0 & 0 & 1 & | & \frac{5}{17} & \frac{4}{17} & -\frac{14}{17} \end{bmatrix} $

5. **Interpretasi Hasil**:
   - Sekarang, bagian sebelah kanan matriks gabungan adalah invers dari matriks awal $ A $. Jadi, invers dari matriks $ A $ adalah:
   $ A^{-1} = \begin{bmatrix} \frac{1}{2} & -\frac{1}{6} & 0 \\ \frac{1}{2} & \frac{1}{6} & -\frac{14}{3} \\ \frac{5}{17} & \frac{4}{17} & -\frac{14}{17} \end{bmatrix} $


# *Penyelesaian Sistem Persamaan Linear Menggunakan Matrix Invers*
Metode invers matriks adalah cara lain untuk menyelesaikan sistem dua persamaan linier. Dalam metode ini, kita menggunakan invers dari matriks koefisien untuk menemukan solusi sistem. Ini berarti jika kita memiliki sebuah matriks $ A $ yang merupakan koefisien dari sistem persamaan, kita mencari invers dari matriks tersebut, dan kemudian mengalikannya dengan matriks hasil ($ B $) untuk mendapatkan matriks yang berisi nilai variabel yang tidak diketahui ($ X $). Jika matriks $ A $ dapat dibalik (determinannya tidak nol), maka kita bisa menggunakan metode ini. Namun, jika determinan matriks $ A $ nol, metode ini tidak berlaku.

Sebagai contoh, jika kita memiliki matriks koefisien $ A = \begin{pmatrix} 2 & -5 \\ -8 & -9 \end{pmatrix} $ dan matriks hasil $ B = \begin{pmatrix} -2 \\ 8 \end{pmatrix} $, kita dapat mencari invers dari matriks $ A $ (jika ada) dan mengalikannya dengan matriks $ B $ untuk menemukan nilai variabel yang tidak diketahui, dalam contoh ini, $ x $ dan $ y $. Jika kita menemukan inversnya ($ A^{-1} $), kita bisa mengalikan $ A^{-1} $ dengan $ B $ untuk mendapatkan matriks $ X $ yang berisi solusi persamaan tersebut.


# *Contoh Penyelesaian Sistem Persamaan linear 4 Variabel dengan Matrix Invers*

Sistem Persamaan Linier 4 variabel

$$5x_1 + 2x_2 + 10x_3 + 16x_4 = 16 \\$$  
$$3x_1 + x_2 - 2x_4 = 4 \\$$
$$3x_1 + x_2 - 9x_3 - 19x_4 = -4 \\$$
$$4x_1 + x_2 - 3x_4 = 5 \\$$

1. kita cari terlebih dahulu untuk invers dari persamaan tersebut


In [2]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped. (menukarkan persamaan)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A (jumlah baris A)
    n = A.shape[1]  # n is number of columns in A (jumlah kolom A)

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale. (mengalikan entry baris A dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modified.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale. (menambahkan nilai baris k dikalikan dengan skala)
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [4]:
# Import library numpy dan memasukkan persamaan dalam bentuk matrix
import numpy as np
A = np.array([[5,2,10,16,1,0,0,0],[3,1,0,-2,0,1,0,0],[3,1,-9,-19,0,0,1,0],[4,1,0,-3,0,0,0,1]])
print(f"Matrix A  = \n{A}")
print("\n")

A1= RowAdd(A,3,0,-1)
print(A1)



Matrix A  = 
[[  5   2  10  16   1   0   0   0]
 [  3   1   0  -2   0   1   0   0]
 [  3   1  -9 -19   0   0   1   0]
 [  4   1   0  -3   0   0   0   1]]


[[  1.   1.  10.  19.   1.   0.   0.  -1.]
 [  3.   1.   0.  -2.   0.   1.   0.   0.]
 [  3.   1.  -9. -19.   0.   0.   1.   0.]
 [  4.   1.   0.  -3.   0.   0.   0.   1.]]


In [6]:
A2= RowAdd(A1,0,1,-3)
print(A2)

[[  1.   1.  10.  19.   1.   0.   0.  -1.]
 [  0.  -2. -30. -59.  -3.   1.   0.   3.]
 [  3.   1.  -9. -19.   0.   0.   1.   0.]
 [  4.   1.   0.  -3.   0.   0.   0.   1.]]


In [7]:
A3= RowAdd(A2,0,2,-3)
print(A3)

[[  1.   1.  10.  19.   1.   0.   0.  -1.]
 [  0.  -2. -30. -59.  -3.   1.   0.   3.]
 [  0.  -2. -39. -76.  -3.   0.   1.   3.]
 [  4.   1.   0.  -3.   0.   0.   0.   1.]]


In [9]:
A4= RowAdd(A3,0,3,-4)
print(A4)

[[  1.   1.  10.  19.   1.   0.   0.  -1.]
 [  0.  -2. -30. -59.  -3.   1.   0.   3.]
 [  0.  -2. -39. -76.  -3.   0.   1.   3.]
 [  0.  -3. -40. -79.  -4.   0.   0.   5.]]


In [10]:
A5= RowAdd(A4,3,1,-1)
print(A5)

[[  1.   1.  10.  19.   1.   0.   0.  -1.]
 [  0.   1.  10.  20.   1.   1.   0.  -2.]
 [  0.  -2. -39. -76.  -3.   0.   1.   3.]
 [  0.  -3. -40. -79.  -4.   0.   0.   5.]]


In [11]:
A6= RowAdd(A5,1,0,-1)
print(A6)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.  10.  20.   1.   1.   0.  -2.]
 [  0.  -2. -39. -76.  -3.   0.   1.   3.]
 [  0.  -3. -40. -79.  -4.   0.   0.   5.]]


In [12]:
A7= RowAdd(A6,1,2,2)
print(A7)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.  10.  20.   1.   1.   0.  -2.]
 [  0.   0. -19. -36.  -1.   2.   1.  -1.]
 [  0.  -3. -40. -79.  -4.   0.   0.   5.]]


In [15]:
A8= RowAdd(A7,1,3,3)
print(A8)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.  10.  20.   1.   1.   0.  -2.]
 [  0.   0. -19. -36.  -1.   2.   1.  -1.]
 [  0.   0. -10. -19.  -1.   3.   0.  -1.]]


In [16]:
A9= RowAdd(A8,3,1,1)
print(A9)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0. -19. -36.  -1.   2.   1.  -1.]
 [  0.   0. -10. -19.  -1.   3.   0.  -1.]]


In [17]:
A10= RowScale(A9,3,2)
print(A10)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0. -19. -36.  -1.   2.   1.  -1.]
 [  0.   0. -20. -38.  -2.   6.   0.  -2.]]


In [18]:
A11= RowAdd(A10,3,2,-1)
print(A11)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0.   1.   2.   1.  -4.   1.   1.]
 [  0.   0. -20. -38.  -2.   6.   0.  -2.]]


In [19]:
A12= RowAdd(A11,2,3,20)
print(A12)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0.   1.   2.   1.  -4.   1.   1.]
 [  0.   0.   0.   2.  18. -74.  20.  18.]]


In [22]:
A13= RowScale(A12,3,1/2)
print(A13)

[[  1.   0.   0.  -1.   0.  -1.   0.   1.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0.   1.   2.   1.  -4.   1.   1.]
 [  0.   0.   0.   1.   9. -37.  10.   9.]]


In [23]:
A14= RowAdd(A13,3,0,1)
print(A14)

[[  1.   0.   0.   0.   9. -38.  10.  10.]
 [  0.   1.   0.   1.   0.   4.   0.  -3.]
 [  0.   0.   1.   2.   1.  -4.   1.   1.]
 [  0.   0.   0.   1.   9. -37.  10.   9.]]


In [24]:
A15= RowAdd(A14,3,1,-1)
print(A15)

[[  1.   0.   0.   0.   9. -38.  10.  10.]
 [  0.   1.   0.   0.  -9.  41. -10. -12.]
 [  0.   0.   1.   2.   1.  -4.   1.   1.]
 [  0.   0.   0.   1.   9. -37.  10.   9.]]


In [25]:
A16= RowAdd(A15,3,2,-2)
print(A16)

[[  1.   0.   0.   0.   9. -38.  10.  10.]
 [  0.   1.   0.   0.  -9.  41. -10. -12.]
 [  0.   0.   1.   0. -17.  70. -19. -17.]
 [  0.   0.   0.   1.   9. -37.  10.   9.]]


2.Setelah kita sudah menemukan inversnya ($ A^{-1} $), kita bisa mengalikan $ A^{-1} $ dengan $ B $ untuk mendapatkan matriks $ X $ yang berisi solusi persamaan tersebut.

$X = A^{-1}B = \begin{bmatrix} 9 & -38 & 10 & 10 \\ -9 & 41 & -10 & -12 \\ -17 & 70 & -19 & -17 \\ 9 & -37 & 10 & 9 \end{bmatrix}$ x $\begin{bmatrix} 16 \\ 4 \\ -4 \\ 5 \end{bmatrix}$

In [29]:
A_inverse = np.array([[9, -38, 10, 10], [-9, 41, -10, -12],[-17, 70, -19, -17], [9,-37,10,9]])
b = np.array([[16], [4], [-4], [5]])

x = A_inverse @ b

print(x)

[[ 2]
 [ 0]
 [-1]
 [ 1]]


# *Referensi*

1). [https://akupintar.id/info-pintar/-/blogs/matriks-pengertian-operasi-determinan-invers-dan-contoh-soal](https://akupintar.id/info-pintar/-/blogs/matriks-pengertian-operasi-determinan-invers-dan-contoh-soal)

2).[https://byjus.com/maths/inverse-matrix/](https://byjus.com/maths/inverse-matrix/)

3). [https://www.brilio.net/ragam/rumus-invers-matriks-pahami-konsep-sifat-dan-contoh-soalnya-2310192.html#:~:text=Beberapa%20sifat%2Dsifat%20invers%20matriks,determinan%20tidak%20sama%20dengan%20nol.](https://www.brilio.net/ragam/rumus-invers-matriks-pahami-konsep-sifat-dan-contoh-soalnya-2310192.html#:~:text=Beberapa%20sifat%2Dsifat%20invers%20matriks,determinan%20tidak%20sama%20dengan%20nol.)

4). [https://www.mathsisfun.com/algebra/matrix-inverse-row-operations-gauss-jordan.html](https://www.mathsisfun.com/algebra/matrix-inverse-row-operations-gauss-jordan.html)

5). [https://ocw.upj.ac.id/files/Slide-IFA104-IFA104-Slide-11.pdf](https://ocw.upj.ac.id/files/Slide-IFA104-IFA104-Slide-11.pdf)

6). [https://youtu.be/4QCjOhi_Qhs?si=Xs3kO6wyUaZmJZ5d](https://youtu.be/4QCjOhi_Qhs?si=Xs3kO6wyUaZmJZ5d)
